### ISSUE TITLE
Screen shakes are missing.

### ISSUE THREAD

**Issue by OpenDUNE** [OpenDUNE/OpenDUNE#131]
http://bugs.opendune.org/view.php?id=131

dsw wrote:
In the original game, the screen would shake vertically when the Map_06F7_08DD function was called (e.g. structure destroyed). However, due to a mistake in r1706, it has evolved into the current Explosion_NoOperation function. The shaking effect is performed by the f__22A6_1200_007B_0356 function, as described below:

emu_cx is number of times to repeat (always 1)
emu_dx is address of VGA base address [0x3D4]
it adds 0x6 to get the CRTC input status register [0x3DA] to test vertical retrace
    (bit 3 == 0 means video information is being displayed
     bit 3 == 1 means vertical retrace interval in progress)
does two blocking loops to wait for vertical retrace to start, then end

subtracts 0x6 to get port 3D4h
disables interrupts
puts 0x1 into Start Address High register
puts 0x40 into Start Address Low register
enable interrupts

add 0x5 to get address to test vertical retrace again [0x3DA]
does four blocking loops for two rounds of vertical retrace

disables interrupts
puts 0x0, 0x0 into Start Address High, Low registers
enable interrupts

decrements emu_cx and loops again if necessary
done

**Comment by miniupnp** [comment]
would it be possible to get SVN history, to dig in what was the code of  the Map_06F7_08DD() function ?

**Comment by Xaroth** [comment]
The entire SVN history was imported as separate commits on github, so it should be findable in the repo log... I doubt there's anything available repo-wise that's not imported into github

**Comment by miniupnp** [comment]
OK, I got it.
https://github.com/OpenDUNE/OpenDUNE/blob/2dc94ceb64a99b61940bd6e090c4fbcc5e839095/decompiled/cs__22A6.c#L2659
It's difficult to search :)

**Comment by miniupnp** [comment]
I think I have a working implementation : 
https://github.com/miniupnp/OpenDUNE/tree/screen_shake
