### ISSUE TITLE
Reference issue, see mantis #140

### ISSUE THREAD

**Issue by OpenDUNE** [OpenDUNE/OpenDUNE#140]
http://bugs.opendune.org/view.php?id=140

**Comment by miniupnp** [comment]
I want to help, but I don't understand what is the problem here...

**Comment by wangds** [comment]
There was some bug with the scripts, introduced somewhere during the 
translation.  I think it caused refineries to sometimes stay in the 
busy state, meaning that harvesters wouldn't automatically return to
it when they were full.

I'm pretty sure it is fixed, can't remember why I reopened it.
Happy to close it.
