### ISSUE TITLE
Resizing of window

### ISSUE THREAD

**Issue by TrueBrain** [OpenDUNE/OpenDUNE#151]
Allow resizing of the window. The current screen can be rather small on modern big displays.

Fullscreen is not really an option, due to WD screens.

Initial work on scale2x has been implemented, and might be considered.

**Comment by miniupnp** [comment]
Isn't setting through opendune.ini enough ?
https://github.com/miniupnp/OpenDUNE/tree/scale2x_hqx

**Comment by miniupnp** [comment]
I think that it's OK now : several scale factors are supported (up to 4x)
windows resize also, and even full screen with some OS
