### ISSUE TITLE
Validate savegames

### ISSUE THREAD

**Issue by TrueBrain** [OpenDUNE/OpenDUNE#160]
Upon loading, validate savegames, as they might be corrupted.

**Comment by miniupnp** [comment]
@TrueBrain what kind of validations should be done ?

**Comment by TrueBrain** [comment]
Any! Now it has none ;)

It was more of a reminder, that it was fully missing, and it was just a hope it all loads correctly. I believe it can even cause buffer overruns, etc :)

But going to close this for now, as it seems a bit far off from the idea of the project, to add such functionality.
