### ISSUE TITLE
New speed system differences.

### ISSUE THREAD

**Issue by wangds** [OpenDUNE/OpenDUNE#168]
Some differences between the old speed system and the new speed system I have found, mostly due to Dune II's low resolution.  I've only tested with quads, so they may well apply to other units too.
1. Quads move faster on the border of rock/sand than on plain rock.  This really is Dune II's fault for penalising wheeled vehicles on "entirely rock" but not on "mostly rock".  On normal speed, rounding errors used to make the two equivalent.  The new system changes that, and looks really odd if you're used to normal speed.
2. Quads move much faster when travelling on sand.  Moving south-east somehow looks very unnatural.
3. Quads sometimes miss the little pause you get after every tile when travelling long distances.
4. Quads moving south or east on sand "pop backwards" as they reach the centre of a tile.

Not sure if you want to consider these bugs or features.

**Comment by miniupnp** [comment]
@wangds @TrueBrain What did you intend to do ?
could you list the issues found in the master branch about speed system ?

**Comment by miniupnp** [comment]
no feedback for more than one year. closing. please reopen if you have some answers

**Comment by rofl0r** [comment]
what's your take on the points i raised in my comment https://github.com/OpenDUNE/OpenDUNE/issues/168#issuecomment-11815259 ?
