### ISSUE TITLE
PlatformToolset = v110_xp

### ISSUE THREAD

**Issue by OlafvdSpek** [OpenDUNE/OpenDUNE#209]
version_vs100.vcxproj doesn't set PlatformToolset, so it defaults to v100 (I think).
opendune_vs100.vcxproj sets PlatformToolset to v110_xp

**Comment by miniupnp** [comment]
@glx22 : does my fix work for your VS Express 2012 ? (I have tested with VS Express 2010)

**Comment by OlafvdSpek** [comment]
I'm currently running 2013 and 2015.

**Comment by glx22** [comment]
For me it works, it uses the platform toolset I set via environment variable PlatformToolset (Windows7.1SDK to be precise). Tested with express 2010, express 2012 and community 2015.

**Comment by miniupnp** [comment]
@OlafvdSpek : does my fix work well for you with 2013 and 2015 ?

**Comment by OlafvdSpek** [comment]
I think the 'fix' is right but I don't know how to test it.

I also noticed VC add a space before the closing />, the Git files are missing this space.

**Comment by miniupnp** [comment]
@OlafvdSpek : It is OK if the project build with your Visual Studio(s)
Without the space before /> it is still correct XML and VC has no problem reading the files

**Comment by OlafvdSpek** [comment]
I know, but it causes unneccesary changes / diffs. ;)

**Comment by miniupnp** [comment]
@OlafvdSpek : is the last patch ok for you ? :)
