### ISSUE TITLE
MessageBox doesn't get focus

### ISSUE THREAD

**Issue by OlafvdSpek** [OpenDUNE/OpenDUNE#210]
The "ERROR LOADING DATA FILE" MessageBox doesn't get focus, so hitting Escape doesn't work.

**Comment by miniupnp** [comment]
I don't know how to fix it... 
Maybe it's related to 1st argument of MessageBox() being NULL ? would it help if it was the handle of main application window ?

**Comment by OlafvdSpek** [comment]
Why is it NULL?

> A handle to the owner window of the message box to be created. If this
parameter is *NULL*, the message box has no owner window.

**Comment by miniupnp** [comment]
@OlafvdSpek : have you tried to set the parameter and see if the behaviour is different ?

**Comment by OlafvdSpek** [comment]
Not yet, will try today. Same for VC2015 fix.

**Comment by miniupnp** [comment]
@OlafvdSpek any update ?

**Comment by OlafvdSpek** [comment]
s_hwnd appears to be NULL at that point, so that's of no use.
The window is created in Video_Tick after the message box is displayed (but before the user has done anything with it).

**Comment by miniupnp** [comment]
Hum I understand the issue.
The window is created in the Video_Tick() and it is created AFTER the messageBox() call.
So the messagebox is created with the focus, and then the application window is created and gets the focus.

**Comment by miniupnp** [comment]
@OlafvdSpek is the fix ok for you ?
