### ISSUE TITLE
Sound-related problems on Windows

### ISSUE THREAD

**Issue by craigo-** [OpenDUNE/OpenDUNE#230]
When running OpenDUNE on my Windows-based EeePC with both music and sound turned on, I frequently get "waveOutOpen failed" popup messages (see attached image.) Once it occurs, clicking on any unit that produces sound generates the popup. Toggling music and sound off and then back on again does not help. The error.log and output.log files remain empty, and no crash dumpfile is produced. Eventually the program starts Not Responding and the only option is to end it.

I have not yet seen the same problem when playing on my desktop PC (Core 2 Duo, 4GB RAM, nVidia Quadro graphics, Windows 7 Enterprise x86).

I have tried MrFlibble's updated VOC files. I believe the frequency of problems reduces when using them, but the problem still occurs.

Environment:
- EeePC 1015 (1GB RAM, Intel graphics @ 1024x600, Realtek High Definition Audio)
- Windows 7 Starter x86
- OpenDUNE 0.7 (release) and pre-v0.8 (built by myself from github source downloaded 2013-05-17)
- Dune 2 1.07 EU game files (as a base)

![opendune_pre0 8_soundfail](https://f.cloud.github.com/assets/4467963/522298/426102ae-c01b-11e2-995f-0acbfe248565.jpg)

**Comment by miniupnp** [comment]
I'm closing, feel free to reopen if the bug is still there in official win32 0.8 release
