### ISSUE TITLE
Port to SDL 2

### ISSUE THREAD

**Issue by silvansky** [OpenDUNE/OpenDUNE#245]
Hi! Do you plan to port OpenDUNE to SDL 2? Once ported it can be built for iOS or Android...

I managed to builld current version for iOS with SDL 2 (with small amount of changes), but I'm not so good in it so the only thing I get is a black screen.

**Comment by wangds** [comment]
I've whipped up something quick here: https://github.com/wangds/OpenDUNE/tree/sdl2
It seems to work, but there are still some issues.

- I'm no good with configure, so I just did a dodgy in config.lib and
  source.list for now, by changing:
    sdl-config -> sdl2-config
    video_sdl.c -> video_sdl2.c

- Arrow keys, F1, F2, F3. don't work.  Letters are fine though.
  Probably everything above 127 in this table: https://wiki.libsdl.org/SDLKeycodeLookup

- Keyboard repeat might also need investigating.

**Comment by pablitox777** [comment]
Think you can update the other repository? Many thanks!

**Comment by OmniBlade** [comment]
For the issues with F1, F2, the arrows and such, couldn't you use SDL scancodes instead of keycodes and create an alternate lookup table for them? Most of them are within the 0-256 range and you could probably ignore those outside that range.

**Comment by miniupnp** [comment]
I'm trying to build : 
```
$ VERBOSE=1 make
make[1]: entrant dans le répertoire « /home/nanard/code/git/OpenDUNE/objs/release »
gcc -O2 -fomit-frame-pointer  -ansi -pedantic -fno-common -Wall -Wsign-compare -Wundef -Wwrite-strings -Wpointer-arith -W -Wredundant-decls -Wformat=2 -Wformat-security -Winit-self -fno-strict-aliasing -Wcast-qual -fno-strict-overflow -Wno-free-nonheap-object -rdynamic -DUNIX -I/home/nanard/code/git/OpenDUNE/include -D_FORTIFY_SOURCE=2 -DWITH_SDL -I/usr/include/SDL2 -D_REENTRANT -DALSA -I /home/nanard/code/git/OpenDUNE/objs/release -c -o audio/mt32mpu.o /home/nanard/code/git/OpenDUNE/src/audio/mt32mpu.c
In file included from /usr/include/SDL2/SDL_main.h:25:0,
                 from /usr/include/SDL2/SDL.h:65,
                 from /home/nanard/code/git/OpenDUNE/src/audio/../os/thread.h:12,
                 from /home/nanard/code/git/OpenDUNE/src/audio/mt32mpu.c:13:
/usr/include/SDL2/SDL_stdinc.h:258:18: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
/usr/include/SDL2/SDL_stdinc.h:289:18: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
```

by removing -ansi I get better results...

**Comment by miniupnp** [comment]
I added  -DSDL_FORCE_INLINE='static __inline'  in the CFLAGS and it works.

**Comment by miniupnp** [comment]
about the keys, see my PR https://github.com/OpenDUNE/OpenDUNE/pull/256
I guess the same could be done for SDL2 (using scancodes directly )

**Comment by miniupnp** [comment]
see PR #257

**Comment by miniupnp** [comment]
@silvansky are you able to build and run on iOS, now ?

**Comment by miniupnp** [comment]
@wangds : I fixed F1/F12/etc. https://github.com/miniupnp/OpenDUNE/commit/bdf7cd1c8d082bbce1c7842a757a8a63acf92ec8
I don't know what to do for keyboard repeat. How to test that ? :)

**Comment by miniupnp** [comment]
see PR #257 
https://github.com/OpenDUNE/OpenDUNE/commit/41bd8f56af4a8d9862166c9fbb2e6102730a4d08

**Comment by drnovice** [comment]
On Visual Studio how can I set SDL2 ?
Apart to include video_sdl2.c instead of video_win32.c, any other operations to works SDL2 with VS compilated in Windows?

**Comment by miniupnp** [comment]
what's the point in compiling for SDL2 under windows.
This has never been tested...

**Comment by drnovice** [comment]
I try to use it, I had to add:
#include <stdio.h>
on top video_sdl2.c because some FILE type definition of functions were ambiguous...
It doesn't find any compiling errors, but game crashes after Intro, and it seems didn't catch mouse motion and keys functions on Main Menu.

**Comment by drnovice** [comment]
"include <stdio.h>"

**Comment by miniupnp** [comment]
I guess there are a lot of place where WIN32 code is assumed as != SDL.
If you really need this, you should open a new ticket like "SDL2 code crashes under windows".
Note : you still haven't explained where's the point in compiling for SDL2 under windows

**Comment by segrax** [comment]
One point in using SDL2 under Windows, is that its much easier to change the window size at runtime... and have SDL take care of the scaling.

is there actually any benefit in having both a Win32I and an SDL version?

**Comment by drnovice** [comment]
The point is: why not? Why only use winapi under Windows and not SDL2? SDL (and OpenGL) is the best crossplatform solution for opensource project, even if it started with Visual Studio under Windows.

As segrax told, SDL2 manages natively scaling/stretching tasks to cover new modern resolutions.
I'll write an openpoint to ask how simply switch from winapi to sdl under windows with visual studio, because I found several problem to compile and run with SDL2 opendune.

**Comment by miniupnp** [comment]
feel free to implement support for windows SDL2

**Comment by drnovice** [comment]
https://github.com/drnovice/OpenDUNE/commits/master
Added SDL2 support for Windows (tested on Win10 x64 and VS2013).
Added scaling by SDL2 for various included filters: nearest, scale2x and hqx.
About scale2x and hqx I only redraw the buffer with magnifier multiplier, and they can go from 2x to 4x, so if player desktop resolution is higher than 4x fullscreen isn't possibile by the way.

**Comment by miniupnp** [comment]
I have to look into this before merging.
how do you select between SDL2 and Win32 API building ?
we don't want to break existing stuff !

**Comment by drnovice** [comment]
By now, only way is remove from build:
video_win32.c
thread_win32.c
and add for build:
video_sdl2.c
thread_sdl.c

I had to add `#include <stdio.h>` on video_sdl2.c because of without it can't complile on VS.

**Comment by drnovice** [comment]
Furthermore I would like give support for SDL1.2 to backward compatibility (same reason to have given support for scale2x and hqx filters), but I can't it work yet.
