### ISSUE TITLE
error C2375: 'snprintf': redefinition; different linkage

### ISSUE THREAD

**Issue by OlafvdSpek** [OpenDUNE/OpenDUNE#254]
VC2015

2>c:\vc\opendune-master\src\os\strings.h(25): error C2375: 'snprintf': redefinition; different linkage
2>  c:\program files (x86)\windows kits\10\include\10.0.10150.0\ucrt\stdio.h(1932): note: see declaration of 'snprintf'
2>c:\vc\opendune-master\src\os\strings.h(43): error C2375: 'vsnprintf': redefinition; different linkage
2>  c:\program files (x86)\windows kits\10\include\10.0.10150.0\ucrt\stdio.h(1426): note: see declaration of 'vsnprintf'

**Comment by miniupnp** [comment]
see if it helps to edit src/os/strings.h 
and add #if _MSC_VER < 1900 / #endif
around snprintf and vsnprintf definitions
_MSC_VER 1900 is for Visual Studio 2015

**Comment by miniupnp** [comment]
@OlafvdSpek : does my patch fixes the problem ?

**Comment by OlafvdSpek** [comment]
Yes, thx
