### ISSUE TITLE
warning C4477: 'sprintf' : format string '%08X' requires an argument of type 'unsigned int', but variadic argument 3 has type 'DWORD64'

### ISSUE THREAD

**Issue by OlafvdSpek** [OpenDUNE/OpenDUNE#255]
2>c:\vc\opendune-master\src\crashlog\crashlog_win32.c(149): warning C4477: 'sprintf' : format string '%08X' requires an argument of type 'unsigned int', but variadic argument 3 has type 'DWORD64'
2>  c:\vc\opendune-master\src\crashlog\crashlog_win32.c(149): note: consider using '%llX' in the format string
2>  c:\vc\opendune-master\src\crashlog\crashlog_win32.c(149): note: consider using '%I64X' in the format string

**Comment by miniupnp** [comment]
try this : 
```
diff --git a/src/crashlog/crashlog_win32.c b/src/crashlog/crashlog_win32.c
index 12cca2a..4a2015d 100644
--- a/src/crashlog/crashlog_win32.c
+++ b/src/crashlog/crashlog_win32.c
@@ -24,7 +24,7 @@ static EXCEPTION_POINTERS *s_ep;
 #define MAX_FRAMES     64
 
 /* printf format specification for 32/64-bit addresses. */
-#ifdef _M_AMD64
+#if defined(_M_AMD64) || defined(_M_X64)
 #define PRINTF_PTR "0x%016IX"
 #else
 #define PRINTF_PTR "0x%08X"
```

**Comment by miniupnp** [comment]
there are other places in crashlog_win32.c whre _M_AMD64 is used

**Comment by miniupnp** [comment]
please check my vs2015 branch https://github.com/miniupnp/OpenDUNE/tree/vs2015
and tell me if it fixes your problems.

**Comment by OlafvdSpek** [comment]
The 32-bit build has warnings:
------ Rebuild All started: Project: opendune, Configuration: Debug Win32 ------
c:\vc\opendune-vs2015\src\ini.c(33): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
c:\vc\opendune-vs2015\src\ini.c(61): warning C4267: 'initializing': conversion from 'size_t' to 'uint16', possible loss of data
c:\vc\opendune-vs2015\src\ini.c(172): warning C4267: 'initializing': conversion from 'size_t' to 'uint16', possible loss of data
c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
c:\vc\opendune-vs2015\src\crashlog\crashlog_win32.c(149): warning C4477: 'sprintf' : format string '%08X' requires an argument of type 'unsigned int', but variadic argument 3 has type 'DWORD64'
  c:\vc\opendune-vs2015\src\crashlog\crashlog_win32.c(149): note: consider using '%llX' in the format string
  c:\vc\opendune-vs2015\src\crashlog\crashlog_win32.c(149): note: consider using '%I64X' in the format string
c:\vc\opendune-vs2015\src\gui\widget_click.c(1310): warning C4267: 'function': conversion from 'size_t' to 'uint16', possible loss of data
c:\vc\opendune-vs2015\src\gui\widget_click.c(1323): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data

**Comment by OlafvdSpek** [comment]
The 64-bit build has more warnings:
------ Build started: Project: opendune, Configuration: Debug x64 ------
..\src\save.c(89): warning C4267: '=': conversion from 'size_t' to 'uint32', possible loss of data
..\src\ini.c(33): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
..\src\ini.c(123): warning C4244: '=': conversion from '__int64' to 'uint16', possible loss of data
..\src\ini.c(61): warning C4267: 'initializing': conversion from 'size_t' to 'uint16', possible loss of data
..\src\ini.c(97): warning C4244: 'initializing': conversion from '__int64' to 'uint16', possible loss of data
..\src\ini.c(172): warning C4267: 'initializing': conversion from 'size_t' to 'uint16', possible loss of data
..\src\file.c(108): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
..\src\audio\mt32mpu.c(130): warning C4244: '=': conversion from '__int64' to 'uint16', possible loss of data
..\src\audio\mt32mpu.c(398): warning C4244: '+=': conversion from '__int64' to 'uint16', possible loss of data
..\src\codec\format80.c(30): warning C4244: '=': conversion from '__int64' to 'uint16', possible loss of data
..\src\codec\format80.c(46): warning C4244: '=': conversion from '__int64' to 'uint16', possible loss of data
..\src\codec\format80.c(59): warning C4244: '=': conversion from '__int64' to 'uint16', possible loss of data
..\src\codec\format80.c(75): warning C4244: '=': conversion from '__int64' to 'uint16', possible loss of data
..\src\codec\format80.c(89): warning C4244: '=': conversion from '__int64' to 'uint16', possible loss of data
..\src\codec\format80.c(97): warning C4244: 'return': conversion from '__int64' to 'uint16', possible loss of data
C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
..\src\gui\widget_click.c(297): warning C4244: 'function': conversion from '__int64' to 'uint16', possible loss of data
..\src\gui\widget_click.c(1310): warning C4267: 'function': conversion from 'size_t' to 'uint16', possible loss of data
..\src\gui\widget_click.c(1323): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
..\src\gui\security.c(137): warning C4267: '=': conversion from 'size_t' to 'uint32', possible loss of data
..\src\gui\security.c(181): warning C4267: '=': conversion from 'size_t' to 'uint32', possible loss of data
..\src\gui\mentat.c(1190): warning C4267: '=': conversion from 'size_t' to 'uint32', possible loss of data
..\src\saveload\scriptengine.c(19): warning C4244: 'return': conversion from '__int64' to 'uint32', possible loss of data
..\src\script\script.c(337): warning C4244: '=': conversion from '__int64' to 'uint32', possible loss of data
..\src\script\script.c(543): warning C4244: 'function': conversion from '__int64' to 'uint16', possible loss of data

**Comment by miniupnp** [comment]
@OlafvdSpek please check my last patch and tell me which warnings are still there.
thx

**Comment by OlafvdSpek** [comment]
I'm a noob, how do I download/apply that patch?
For the branch I just downloaded the .zip

**Comment by miniupnp** [comment]
I've put to the branch, so you can download the zip again.

but please setup git ! https://git-scm.com/download/win

**Comment by miniupnp** [comment]
in git bash:
```
$ git clone https://github.com/OpenDUNE/OpenDUNE.git
...
$ cd OpenDUNE
$ git remote add miniupnp https://github.com/miniupnp/OpenDUNE.git
$ git fetch --all --prune
$ git checkout -b vs2015 miniupnp/vs2015
```
From then you are in my "vs2015" branch, you only need to "git pull" to update.
use git checkout to switch branches (git checkout master / git checkout vs2015)

**Comment by OlafvdSpek** [comment]
32-bit:
2>c:\vc\opendune-vs2015\src\crashlog\crashlog_win32.c(149): warning C4477: 'sprintf' : format string '%08X' requires an argument of type 'unsigned int', but variadic argument 3 has type 'DWORD64'
2>  c:\vc\opendune-vs2015\src\crashlog\crashlog_win32.c(149): note: consider using '%llX' in the format string
2>  c:\vc\opendune-vs2015\src\crashlog\crashlog_win32.c(149): note: consider using '%I64X' in the format string

64-bit is clean except for a warning in a system header (damn MS)

Git was installed already but I'm still trying to figure out how it works. Thx!

**Comment by miniupnp** [comment]
@OlafvdSpek my advice is to use git bash. once the repository is set with the "remote" added, just use git pull / git checkout <branch>
and of course git status to check that everything is OK. that's not that complicated !!!

**Comment by miniupnp** [comment]
@OlafvdSpek : I updated the branch. please tell me if the warning is gone

**Comment by OlafvdSpek** [comment]
Nope:
..\src\crashlog\crashlog_win32.c(149): warning C4477: 'sprintf' : format string '%08IX' requires an argument of type 'unsigned int', but variadic argument 3 has type 'DWORD64'
  ..\src\crashlog\crashlog_win32.c(149): note: consider using '%llX' in the format string
  ..\src\crashlog\crashlog_win32.c(149): note: consider using '%I64X' in the format string

**Comment by miniupnp** [comment]
what it you replace 
#define PRINTF_PTR "0x%08IX"
by 
#define PRINTF_PTR "0x%08I64X"
 ?

**Comment by OlafvdSpek** [comment]
That does the trick
