### ISSUE TITLE
ready for 0.8 release ?

### ISSUE THREAD

**Issue by miniupnp** [OpenDUNE/OpenDUNE#263]
Could the current code be released as v0.8 ?

**Comment by miniupnp** [comment]
@Xaroth do you have an opinion about this ?

**Comment by Xaroth** [comment]
@miniupnp I personally don't mind; it's been a few years since the last release, so a 0.8 would possibly put some new life in things, but I'll discuss it with @TrueBrain when I talk to him next

**Comment by TrueBrain** [comment]
Please, do feel free to make a new release at any point in time you deem useful :)

Sadly, I am of little help to you making the actual release. The ways we used to do it (5 years ago now :o I am growing old ..) are long gone, so you will have to look for it yourself a bit. If I remember correctly, 'make bundle' should work, and then it is a matter of doing that on all OSes you fancy (and MSVC for Windows builds ofc). I used to do the Mac builds on my old laptop :D (but it died years ago)

I also just uploaded all binaries I had for the older releases on Github, so you have a bit of a history there again. Hope that helps.

Any questions, feel free to bug @Xaroth ;) :D

**Comment by miniupnp** [comment]
I think I will release 0.8 soon ;)
I have trouble compiling OS X "universal" binaries, I'm trying to fix that

**Comment by tekbj80** [comment]
Hi @miniupnp , I'm really new to this... I've been trying to get this to run on MacOS for the last hour, and did not get any progress. I've tried to follow the README but it's not getting me anywhere... 

I'm also new to github, and I am not sure how to contact anyone here... I know this is not the right place for my request for help... So, kindly let me know where I can write for help... or if I should open an issue for this... 

Thanks!

**Comment by miniupnp** [comment]
This "issue" is definitely not the right place ;)
if "make" doesn't work, please open a new issue with all details : OS X version, XCode version, output of "make" command.
Nobody can help you if you don't give more details than "I did not get any progress" ;)

**Comment by tekbj80** [comment]
Sorry for asking this here before... and as for the "doesn't work"... was more like I didn't know what I need to do after cloning the repo... 

If you didn't mention `make`, I think I might have just given up on this. What would you think if I a open an issue to add this in the `README.txt`?
