### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by stefan-reich** [OpenDUNE/OpenDUNE#276]
https://medium.com/@stefanreich/a-world-without-compiling-c-code-973cf1b20571#.a8oouc5ff

**Comment by Xaroth** [comment]
Without a real traceback or logs or anything, it's pretty hard for anybody to make heads or tails out of this. 
Also, please keep in mind that we have some precompiled binaries for several platforms that you can find here: https://github.com/OpenDUNE/OpenDUNE/releases

**Comment by miniupnp** [comment]
looks like your compiler has issue with MMX/SSE intrinsics. But your report is useless without details : which OS, which compiler, etc.

**Comment by Xaroth** [comment]
Seeing this issue has not had a response in almost a month, I'm closing this.
