### ISSUE TITLE
"datadir" setting is relative to ./data/ folder

### ISSUE THREAD

**Issue by Nyerguds** [OpenDUNE/OpenDUNE#277]
When I edited the ini and put "./data" in the "datadir" setting, it tried to access a "./data/data" folder. It should take ./data as _default_, but not as _base_ for the _given_ folder.

The "savedir" setting has no such issue, and uses the launch folder as base.

On a related note, it'd be nice if the game took the location of its own binary as base folder, rather than the folder it's _launched_ from.

**Comment by miniupnp** [comment]
well there is room for improvement on the subject.
we could allow directories to be absolute (begin with / or X:\) , relative to binary or relative to current directory (./ )

**Comment by Nyerguds** [comment]
The datadir one is definitely a bug though... there's no logic behind "relative to the data/ subfolder of the current directory"
