### ISSUE TITLE
Indestructible enemy buildings

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [OpenDUNE/OpenDUNE#279]
At the end of the second Harkonnen mission against Ordos the player can not destroy enemy buildings (has full hp and seems indestructible).

I also encountered a problem that the enemy built a building across the player's units.

Game save:
[_SAVE002.ZIP](https://github.com/OpenDUNE/OpenDUNE/files/636350/_SAVE002.ZIP)

**Comment by miniupnp** [comment]
well indeed. You destroyed all other Ordos buildings, right ?
what version of OpenDUNE did you use to make this savegame ?

**Comment by eLEcTRiCZiTy** [comment]
All other enemy buildings are destroyed.

Sorry, the device on which I played, is currently unavailable.
Savegame is from a game version downloaded the day I created this issue.

**Comment by miniupnp** [comment]
which OS ?

**Comment by miniupnp** [comment]
looks like the buildings are not indestrutible but have 10000+ life points.
it should be 100 or something...
I'm waiting, they will finally be destroyed :)
I need to know which OpenDUNE version you used. Which OS, which downloaded file

**Comment by puddlecoded** [comment]
I've also experienced the indestructible building issue, OSX findversion.sh says 1

**Comment by miniupnp** [comment]
@puddlecoded so you have OS X. Which version ? 
have you downloaded a ecompiled package ? or compiled from sources ? which sources (git checkout ?)

**Comment by puddlecoded** [comment]
10.12.3 Compiled from source => downloaded master

**Comment by miniupnp** [comment]
thx

**Comment by svuorela** [comment]
I've seen it with befd66162a31352e7522978e1b54d0686704f478 - they weren't indestructible, but took 20 or so minutes each with quite an army.

**Comment by miniupnp** [comment]
It is possible there is garbage in your scenario files
hitpoints are loader there :
https://github.com/OpenDUNE/OpenDUNE/blob/master/src/scenario.c#L260

**Comment by miniupnp** [comment]
OK it is that. Some scenario have strange values...

```
Scenario_Load_Structure ID001 Ordos,Const Yard,8421,936
hitpoints=8421 => 13157
Scenario_Load_Structure ID000 Ordos,Light Fctry,14058,1064
hitpoints=14058 => 19219
Scenario_Load_Structure ID036 Harkonnen,Const Yard,256,3234
hitpoints=256 => 400
Scenario_Load_Structure ID014 Ordos,Windtrap,256,1253
hitpoints=256 => 200
Scenario_Load_Structure ID012 Ordos,Windtrap,256,1255
hitpoints=256 => 200
Scenario_Load_Structure ID010 Ordos,Spice Silo,256,933
hitpoints=256 => 150
Scenario_Load_Structure ID009 Ordos,Refinery,256,1124
hitpoints=256 => 450
Scenario_Load_Structure ID007 Ordos,Barracks,256,1257
hitpoints=256 => 300
Scenario_Load_Structure ID002 Ordos,Outpost,256,1382
hitpoints=256 => 500

```

**Comment by miniupnp** [comment]
That's a kind of bug in One scenario : 
```
/EXTRACT/SCENARIO$ grep ID * |grep -v 256
SCENH006.INI:ID001=Ordos,Const Yard,8421,936
SCENH006.INI:ID000=Ordos,Light Fctry,14058,1064
SCENO001.INI:ID036=Harkonnen,Trooper,199,1488,64,Ambush
SCENO001.INI:ID035=Harkonnen,Trooper,199,1633,64,Ambush
SCENO001.INI:ID034=Harkonnen,Trooper,142,1878,64,Ambush
SCENO001.INI:ID032=Harkonnen,Trooper,199,2090,64,Ambush
SCENO001.INI:ID023=Harkonnen,Trooper,85,2839,64,Ambush
SCENO002.INI:ID037=Harkonnen,Quad,216,1511,160,Area Guard
SCENO002.INI:ID040=Harkonnen,Quad,216,1126,160,Area Guard
SCENO003.INI:ID026=Harkonnen,Trooper,199,2539,64,Area Guard
SCENO003.INI:ID031=Harkonnen,Trooper,142,2341,64,Ambush

```

**Comment by miniupnp** [comment]
@TrueBrain as you are the author of the original modification, what do you think ?
We could fix the problem with 
`if(hitpoints > 256) hitpoints = 256;`
as it is meaning less to have more than 100% "life"
