### ISSUE TITLE
Fullscreen instead of a window on startup?

### ISSUE THREAD

**Issue by Rezolyze** [OpenDUNE/OpenDUNE#282]
How about putting an option in the "opendune.ini" that starts the game in fullscreen instead of a window? I know that I can press Alt+Enter to go to fullscreen mode, or I could compile with "static bool s_full_screen = true;" as the default. However, it would be nicer to have this as an option in the "ini" or as a command line switch.

I guess this enhancement would be possible if/when issue #259 is implemented, but that seems like a larger task.

In case it matters, I'm using "opendune-0.8-linux-amd64-sdl-pulse.tar.bz2" with the EU data on Linux Mint 18.1 Cinnamon 64-bit. Thanks to all the contributors for working on this program. This game is awesome and so are you!

**Comment by miniupnp** [comment]
We also need to add fullscreen under windows, either supporting SDL/SDL2 with windows or doing GDI full screen which should be possible also using ChangeDisplaySettings()  : 
https://www.gamedev.net/topic/150836-full-screen-in-gdi/

**Comment by miniupnp** [comment]
windows support for fullscreen : https://github.com/miniupnp/OpenDUNE/commit/e08009b29285a0c59642855b4bccdd0f84d8d27b

**Comment by drnovice** [comment]
There is a PR to support SDL/SDL2 on Windows and making Fullscreen/Zooming In/Out support:
https://github.com/OpenDUNE/OpenDUNE/pull/281
