### ISSUE TITLE
Cannot compile opendune on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by drnovice** [OpenDUNE/OpenDUNE#283]
I'm Installed Ubuntu 16.04 TLS. I tried both 32/64 bit distro.
After creating Makefile with **./configure** bash command, when I try to compile opendune sources by "**make**" command, I got this error:
```
drnovice@tortuga-vm:~/test/OpenDUNE$ make
make[1]: ingresso nella directory "/home/drnovice/test/OpenDUNE/objs/release"
[SRC] Compiling and linking depend
[SRC] DEP CHECK (all files)
[SRC] Compiling animation.c
[SRC] Compiling audio/driver.c
[SRC] Compiling audio/dsp_pulse.c
[SRC] Compiling audio/midi_alsa.c
In file included from /usr/include/alsa/asoundlib.h:54:0,
                 from /home/drnovice/test/OpenDUNE/src/audio/midi_alsa.c:8:
/usr/include/alsa/pcm.h:1010:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void snd_pcm_pack_audio_tstamp_config(unsigned int *data,
               ^
/usr/include/alsa/pcm.h:1018:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void snd_pcm_unpack_audio_tstamp_report(unsigned int data, unsign
               ^
Makefile:179: set di istruzioni per l'obiettivo "audio/midi_alsa.o" non riuscito
make[1]: *** [audio/midi_alsa.o] Errore 1
make[1]: uscita dalla directory "/home/drnovice/test/OpenDUNE/objs/release"
Makefile:43: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 1
```
I installed SDL2 by command: **sudo apt-get install libsdl2-dev**
What else do I need?

**Comment by miniupnp** [comment]
does your system use pulseaudio ?
In that case you need to install libpulse-dev as well

**Comment by drnovice** [comment]
libpulse-dev already installed into Ubuntu:
`drnovice@tortuga-vm:~$ sudo apt-get install libpulse-dev
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
libpulse-dev is already the newest version (1:8.0-0ubuntu3.2).
È stato impostato libpulse-dev per l'installazione manuale.
0 aggiornati, 0 installati, 0 da rimuovere e 78 non aggiornati.
`
configure output (pulse found):
`drnovice@tortuga-vm:~/test/OpenDUNE$ ./configure
checking awk... awk
detecting OS... UNIX
checking build system type... x86_64-linux-gnu
checking host system type... x86_64-linux-gnu
checking universal build... no
checking build cc... gcc
checking host cc... gcc
checking strip... disabled
checking builtin depend... yes
checking makedepend... disabled
detecting cpu-type... 64 bits
checking static... no
using debug level... no
disabling asserts
using link time optimization... no
checking OSX sysroot... not OSX, skipping
checking SDL2... found
checking SDL... disabled
checking asound... found
checking oss... not found
checking pulse... found
checking munt... not found
checking GDI video driver... not Windows, skipping
checking assert... disabled
checking sort... sort
checking stripping... skipped
checking distcc... no (only used when forced)
checking ccache... no (only used when forced)
checking revision... git detection
installation directory... /
gcc
using CFLAGS_BUILD...  -ansi -pedantic -fno-common -Wall -Wsign-compare -Wundef -Wwrite-strings -Wpointer-arith -W -Wredundant-decls -Wformat=2 -Wformat-security -Wno-format-nonliteral -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -Winit-self -fno-strict-aliasing -Wcast-qual -fno-strict-overflow -Wno-free-nonheap-object -rdynamic -D_FORTIFY_SOURCE=2 -O1 -DNDEBUG
using LDFLAGS_BUILD...  -rdynamic
using CFLAGS... -O2 -fomit-frame-pointer -Wno-variadic-macros  -ansi -pedantic -fno-common -Wall -Wsign-compare -Wundef -Wwrite-strings -Wpointer-arith -W -Wredundant-decls -Wformat=2 -Wformat-security -Wno-format-nonliteral -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -Winit-self -fno-strict-aliasing -Wcast-qual -fno-strict-overflow -Wno-free-nonheap-object -rdynamic -DUNIX -I/home/drnovice/test/OpenDUNE/include -D_FORTIFY_SOURCE=2 -DWITH_SDL2 -I/usr/include/SDL2 -D_REENTRANT -DSDL_FORCE_INLINE='static __inline' -DALSA -D_REENTRANT -DPULSEAUDIO -DNDEBUG
using LDFLAGS...  -L/usr/lib/x86_64-linux-gnu -lSDL2 -lSDL2_image -lasound -lpulse  -rdynamic
Generating Makefile...
Generating objs/Makefile...
`
Anyway I think problem is alsa headers, into /usr/include/alsa

**Comment by miniupnp** [comment]
you can remove -ansi and -pedantic copilation options, I'm sure it will fix the problem :)

**Comment by drnovice** [comment]
Why put that strict option by default, if then we have to remove them to compile with newest Linux releases?

**Comment by miniupnp** [comment]
I'm not the one who put theses compilation options...
And I'm quite sure Ubuntu 16.04 LTS was not out at that time !

**Comment by drnovice** [comment]
Of course... :)
