### ISSUE TITLE
Non-qwerty keyboard layout support on Linux

### ISSUE THREAD

**Issue by Walkman100** [OpenDUNE/OpenDUNE#284]
I have a Dvorak keyboard, and have the system set up to use it, but OpenDune gets my input as if it's Qwerty, typing "Walkman":
![image](https://user-images.githubusercontent.com/5454764/29489685-f90d6c3e-8526-11e7-914f-c948c8718d4d.png)
typing "None":
![image](https://user-images.githubusercontent.com/5454764/29489690-0bd2ad52-8527-11e7-953d-5d220dc97daf.png)
(I have no idea what the answers to any of these questions are btw)

My input config:
![image](https://user-images.githubusercontent.com/5454764/29489747-2931134c-8528-11e7-81d7-f6c64ae05929.png)

Using Linux Mint 17.3 Rosa, Qt: 4.8.6, KDE Development Platform: 4.14.2, Plasma Desktop Shell: 4.11.11, IBus 1.5.5

Using OpenDune v0.8 (from the title bar, `opendune --version` starts up the game as normal) from [release v0.8](https://github.com/OpenDUNE/OpenDUNE/releases/tag/0.8) with data files from [Abandonia](http://www.abandonia.com/en/games/36/Dune+II+-+The+Building+of+a+Dynasty.html)

```
> uname -a
Linux WalkmanLM17 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Walkman100** [comment]
I have a few other bugs, should I make issues for them? I won't bother if no one's working on this or they won't help anyone. I have no music, and some of the arrow keys don't work as expected. I'd also like to request a few features, like command-line support for options, skipping the cutscene at the beginning, key rebinding, setting the game zoom factor in the game settings e.t.c.

**Comment by Walkman100** [comment]
Also fullscreen bugs out pretty badly, it disables the keyboard until I restart the game, and it doesn't fill up the screen or cover the windows beneath it, so I see parts of the underlying window around the border of the game.

**Comment by miniupnp** [comment]
I don't know if the original Dune II supports non US-QWERTY keyboard layouts.
We are using code translated from the original Dune II
I will have a look at what it is possible to do.

By the way, are you using SDL or SDL2 ?

About other bugs, please open other issues.

**Comment by miniupnp** [comment]
https://github.com/miniupnp/OpenDUNE/commits/crack

**Comment by Walkman100** [comment]
Sorry about the late reply.
I'm using SDL2:
```
> apt show libsdl2-2.0-0
Package: libsdl2-2.0-0
State: installed
```

**Comment by miniupnp** [comment]
@Walkman100 have you tried the original Dune II game with your keyboard (in DOS or with DOSBox) ?

**Comment by Walkman100** [comment]
Just tested this on Windows, it gets my keyboard input fine. No I haven't tried the original Dune II in DOSBox, however I do remember DOSBox on my Linux install got my keyboard input as if I was using a Qwerty layout too... hmm...

**Comment by miniupnp** [comment]
Dune II / OpenDUNE is  using its own code to translate XT/AT keyboard scancodes to it's how key codes and then ASCII values :
 https://github.com/miniupnp/OpenDUNE/blob/fa9c2e4bb7c62b9eae9eb4d2f4cec2d0092f5c55/src/input/input.c#L61
It is using the US QWERTY Keyboard layout.
