### ISSUE TITLE
Feature Request: arrow key support

### ISSUE THREAD

**Issue by Walkman100** [OpenDUNE/OpenDUNE#286]
Currently, the arrow keys have this effect in game:
Up: moves the screen up
Down: nothing
Right: moves the screen diagonally down and to the right
Left: moves the screen diagonally up and to the right
It would be great to be able to use the arrow keys to move around the map properly.

What would also be awesome, is being able to rebind keys. I doubt that is likely to happen though, since that probably requires a large amount of modification to the code.

**Comment by miniupnp** [comment]
well I just tested on my FreeBSD machine and it works well. I don't remember such a bug neither on windows, linux, macos or Atari :)
What's your configuration. Are you using SDL, SDL2 ?

**Comment by Walkman100** [comment]
SDL2 on Linux Mint 17.3 Rosa KDE 4.14.2, I'll test it on my windows install in a few days. It might have to do with my Dvorak keyboard layout

**Comment by miniupnp** [comment]
bug not confirmed.
@Walkman100 compile a debug build and look at scancodes you've got from your keyboard...

**Comment by Walkman100** [comment]
Just tested it on Windows, Arrow keys work as expected... I'll have to do that when I reboot into Linux, hopefully that won't be more than a few days...
