### ISSUE TITLE
Feature Request: Options on the command line

### ISSUE THREAD

**Issue by Walkman100** [OpenDUNE/OpenDUNE#287]
#259 is probably a good idea to implement first, but it would be great to be able to apply options to the game on the command line instead of having to edit the configuration file every time.

Right now, `opendune --help` launches the game as usual.
Setting options could be done like this: `opendune --scalefactor=4` and `opendune --scalefilter=scale2x` to test these options before changing the config file.

**Comment by miniupnp** [comment]
I remember @TrueBrain was not in favor for command line options, but preferred the .ini file way of setting options.

**Comment by TrueBrain** [comment]
Either use one way, or go home, indeed :) The ini is full of very specific settings, so why start to make an exception here now :)
