### ISSUE TITLE
Error compiling midi_alsa.c

### ISSUE THREAD

**Issue by monreal** [OpenDUNE/OpenDUNE#291]
```
[SRC] Compiling audio/driver.c
[SRC] Compiling audio/dsp_pulse.c
[SRC] Compiling audio/midi_alsa.c
In file included from /usr/include/alsa/asoundlib.h:54:0,
                 from /home/micmon/code/gaming/OpenDUNE.git/src/audio/midi_alsa.c:8:
/usr/include/alsa/pcm.h:1010:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void snd_pcm_pack_audio_tstamp_config(unsigned int *data,
               ^~~~
/usr/include/alsa/pcm.h:1018:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void snd_pcm_unpack_audio_tstamp_report(unsigned int data, unsigned int accuracy,
               ^~~~
make[1]: *** [Makefile:180: audio/midi_alsa.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/micmon/code/gaming/OpenDUNE.git/objs/release'
make: *** [Makefile:43: all] Error 1
```

I can compile fine when using --without-asound

**Comment by miniupnp** [comment]
which OS / Distrib, wich compiler version, etc.

**Comment by monreal** [comment]
gcc 7.2.1 on Fedora 27

**Comment by miniupnp** [comment]
I guess you can try to remove the -ansi and -pedantic CFLAGS...

**Comment by monreal** [comment]
Without those flags it builds fine

**Comment by flip111** [comment]
Can this issue be reopened? It's still persistent.

Related:
https://github.com/OpenDUNE/OpenDUNE/issues/283
https://github.com/OpenDUNE/OpenDUNE/issues/266

**Comment by flip111** [comment]
Installation instructions for ubuntu 16.04:

1. edit config.lib and remove -ansi and -pendantic flags
2. `sudo apt install libsdl2-image-dev`
3. do something to make MIDI working. readme suggest installing ALSA driver or MUNT. But have yet to find instructions for that.
4. move bin directory anywhere on disk (make install is missing)
5. for fullscreen:
```
cat <<EOT >> ~/.config/opendune/opendune.ini
[opendune]
fullscreen=1
EOT
```

Not sure yet what are the best settings to get the best graphics, especially related to `scalefactor` and `scalefilter`

If anyone has additional info one some of the missing things here would be appreciated. So far i don't have a game with working sound looking good on fullscreen.

**Comment by miniupnp** [comment]
"get the best graphics" is extremely suggestive. just try et use whatever you like best.

make install is not missing
