### ISSUE TITLE
Game crash at the beginning of mission 8

### ISSUE THREAD

**Issue by MBach** [OpenDUNE/OpenDUNE#292]
After battle 7 (see below) and just when mission 8 (no screen) is starting, I encountered a crash on pre 0.9 (built by myself).

![image](https://user-images.githubusercontent.com/1532657/32622945-e95f2590-c584-11e7-9e02-377044b96d8c.png)

I have uploaded the crash.dmp here
http://bachelierm.free.fr/crash.dmp

**Comment by miniupnp** [comment]
It is playing attreides, right ?
so you built on windows using which compiler ?
which git commit ?

**Comment by MBach** [comment]
Yes, I'm playing the Attreides
I used Visual Studio 2015 and MSVC 14 (I did the build using opendune_vs140)
Git commit: https://github.com/OpenDUNE/OpenDUNE/commit/67c85cc0a30dee57b64d5fb0bffcf823afe7e9a0 (10 commits behind master)

After the end of mission 7, I have 3 choices for the next mission, where I have to defeat Ordos. When it crashed, it was the one at the bottom (bottom, corner bottom-right, and right).

Today, I have completed once again the mission 7 and I have selected another choice: corner bottom-right, and it didn't crash!

**Comment by miniupnp** [comment]
could you attach your savegame ?
also if you have VS you should "Debug". VS should tell you where the crash is...

**Comment by MBach** [comment]
Is savegame stored in some special place? I though it was under data\_SAVE000.DAT but it I delete it and restart the game I still have everything.

Anyway, with Visual Studio, it seems to point the function `GameLoop_house(void)` from `house.c`, and the line 219 was highlighted:

    if (tickStarport && h->starportLinkedID != UNIT_INDEX_INVALID) {

**Comment by miniupnp** [comment]
save games are saved in  %APPDATA%\OpenDUNE

and h is null ?

**Comment by MBach** [comment]
![image](https://user-images.githubusercontent.com/1532657/32632757-17898e5e-c5a5-11e7-9065-6714ddaafc95.png)

**Comment by miniupnp** [comment]
that is strange that h points to unreadable memory...

hum couldn't you save just before wining ? :) I'll wait tomorrow to have time to finish this mission :)

**Comment by miniupnp** [comment]
@MBach have you the same bug when compiled in Win32 (not x64) ?

**Comment by MBach** [comment]
Actually I have tried the 3 choices after this mission, and I couldn't make it crash again, still in 64-bit. Very odd

**Comment by MBach** [comment]
I had multiple crashes during next mission, where I fight both Harkonnen and Ordos houses. But it doesn't properly crash, it's just the window is freezing, so I have to manually shut down the app.

How can I run the game with the debugger in real time? If I press the Play icon in visual studio, at startup, the game keeps telling me that I need to put original Dune files in data folder. I've tried to put in every subfolder but I cannot make it work. Any tip for debugging?

**Comment by miniupnp** [comment]
well... why don't you put the Dune II files in data folder ?
Or change the working directory ?

**Comment by miniupnp** [comment]
Here is where I set the working directory in Visual Studio 2010 (French version) :
![image](https://user-images.githubusercontent.com/1070377/32773757-7f715f0a-c92a-11e7-8049-052bdf736bf1.png)

**Comment by MBach** [comment]
Because it's not working out of the box! I had to manually hardcode path when looking for opendune.ini in the project to "c:/<my path>/Debug/Win32/". Then, in opendune.ini I've set the data path to the subfolder data.

This is quite strange because the executable is working without any issue if I open if manually like any other application. Unfortunately, when the game is freezing, there must be an infinite loop somewhere, because the app is not crashing but not responding either.

**Comment by miniupnp** [comment]
By default, OpenDune look for files in a data/ subdirectory of the Working directory.
You can set the working directory in Visual studio. (I think by default it is the directory where the .exe is build, ie xxx/Debug or xxx/Release)

But you can also set the path using the datadir= option in opendune.ini

opendune.ini is searched in several locations : 
https://github.com/OpenDUNE/OpenDUNE/blob/master/src/inifile.c#L35

just set relevant breakpoints in file.c (File_MakeCompleteFilename() and  File_Init()) if you still cannot get it
