### ISSUE TITLE
WinApi toggle fullscreen doesn't work for scale2x & hqx filters

### ISSUE THREAD

**Issue by drnovice** [OpenDUNE/OpenDUNE#295]
Since last changes (2nd November 2017), WinApi toggle fullscreen doesn't work for **scale2x** and **hqx filters**:

![opendune_scale2x_winapi_fullscreen](https://user-images.githubusercontent.com/4188231/33088003-9b8c87d8-ceec-11e7-8879-9be7f618c4a0.png)

**Comment by drnovice** [comment]
Compiled and tested with VS2013 & VS2015.

**Comment by timofonic** [comment]
@drnovice @miniupnp Any news about this?

**Comment by miniupnp** [comment]
@timofonic see my branch https://github.com/miniupnp/OpenDUNE/tree/issue_295
