### ISSUE TITLE
Game stuck in house selection screen

### ISSUE THREAD

**Issue by svuorela** [OpenDUNE/OpenDUNE#296]
Tried self compiled 0.8 and befd66162a31352e7522978e1b54d0686704f478 (recent master)

Seems to be stuck in 

`(gdb) bt`
`#0  0x00007ffff70551d0 in __pause_nocancel () at ../sysdeps/unix/syscall-template.S:84`
`#1  0x00005555555ac9ea in SleepAndProcessBackgroundTasks () at /home/sune/git/OpenDUNE/src/timer.c:159`
`#2  0x00005555555785e8 in GUI_PickHouse () at /home/sune/git/OpenDUNE/src/gui/gui.c:1721`
`#3  0x0000555555598095 in GameLoop_Main () at /home/sune/git/OpenDUNE/src/opendune.c:1013`
`#4  0x00005555555988d0 in main (argc=1, argv=0x7fffffffdfa8) at /home/sune/git/OpenDUNE/src/opendune.c:1303`

**Comment by miniupnp** [comment]
I guess you have a sound problem.
The game waits for the house name sound to be finished before proceeding

**Comment by miniupnp** [comment]
@svuorela are you using the pulse audio / oss / alsa or SDL sound ? :)

**Comment by xcom169** [comment]
I have sound problem too. Midi is working, but speech is not. Can you help?

**Comment by miniupnp** [comment]
@xcom169 what speech "driver" are you using ? timidity is for Midi

**Comment by xcom169** [comment]
Well, I don't know which speech driver am I using, but speech is generally working fine. Only if I start timidity  then eg. 'House Harkonnen' speech is stuck, and the game freezes. So speech and sound together is not working on Linux. On Windows it's working for me. 
I found some suggestions to run Timidity in alsa output mode. Do you think that will help?

**Comment by miniupnp** [comment]
@xcom169 try to recompile with or without Pulseaudio support

**Comment by xcom169** [comment]
With timidity -iA it works! 
Should I change my Ubuntu Timidty service, or should recompile it without pulseaudio ?

**Comment by miniupnp** [comment]
I should add a notice in the README to warn about the problem of sound not playing and blocking the game in the house selection screen
