### ISSUE TITLE
Binaries and/or Build instructions?

### ISSUE THREAD

**Issue by mkrupczak3** [OpenDUNE/OpenDUNE#297]
Sorry if this may seem a bit trivial, but are there any instructions anywhere for how to build from source? Or otherwise, are there binaries of the latest version(s) available for download anywhere?

**Comment by miniupnp** [comment]
To build :
unix : ./configure && make
windows/Visual studio : use the proper project/solution file from projets subdirectory.

The binaries are available for download on github.
