### ISSUE TITLE
ini ?

### ISSUE THREAD

**Issue by dejo01** [OpenDUNE/OpenDUNE#312]
I played around some of the ini parameters but almost nothing seems to work.
Specifically, scalefactor and scalefilter work fine but what is _dune2_enhanced_ supposed to do? I tried both 0 and 1 but I don't see any difference in gameplay.
Also, none of the debug options seem to make any difference.
Finally, fullscreen doesn't work at all. I tried _fullscreen=1_, Alt+Enter, F11. I am on Windows 7 64-bit.

Am I missing something?

**Comment by miniupnp** [comment]
What is the version you tested ?

setting _dune2_enhanced=0_ enable some original Dune2 **bugs**  !
you could check in the source code what bugs are "fixed" https://github.com/OpenDUNE/OpenDUNE/search?q=g_dune2_enhanced&type=Code
Full screen does work under win32... what's your screen resolution ? 
Please also check error.log / output.log

**Comment by dejo01** [comment]
I downloaded v0.8 win64 from [here](https://github.com/OpenDUNE/OpenDUNE/releases). I don't have Visual Studio so I can't compile the source.
My resolution is 1920x1080.
error.log contains the phrase _Useless GFX_SetPalette() call_ several times and output.log: _Thank you for playing Dune II._

**Comment by miniupnp** [comment]
@dejo01  0.8 is very old now. It doesn't support the debug opendune.ini options, nor win32 fullscreen.

you can download Visual Studio community for free : https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15
