### ISSUE TITLE
no linux executable?

### ISSUE THREAD

**Issue by jason-mehmel** [OpenDUNE/OpenDUNE#313]
Hi there!

I downloaded OpenDUNE but can't find an executable to start running the game. There's the opendune.ini.smaple in the bin folder but I'm not sure if I'm supposed to generate an executable first or not.

**Comment by miniupnp** [comment]
$ ./configure
$ make
$ make run

**Comment by jason-mehmel** [comment]
Thanks for this! I'm getting some errors from that. Should I report them here or start a new issue?

**Comment by miniupnp** [comment]
make sure you have SDL or SDL2 (the development packages) on your linux.
Please open a new issue with full log if you build fails.

**Comment by yigitsever** [comment]
> $ ./configure
$ make
$ make run

this might not be common knowledge (wasn't for me), would you care to include it somewhere?

**Comment by miniupnp** [comment]
@yigitsever might not be common knowledge ? are you serious ? http://bfy.tw/IQVv

This project is maybe 10 years old, and nobody ever thought about writing down that you should use configure and make to build... but it indeed might be useful.
But the best advice I can give you is to ask for your linux distribution to package OpenDUNE, so you won't bother building it from sources.
