### ISSUE TITLE
Compile errors on macos

### ISSUE THREAD

**Issue by lviolinisparkdigital** [OpenDUNE/OpenDUNE#314]
Hi,
I'm trying to compile OpenDune but I'm not able to. I wonder if there's something funny going on with my environment, or is it perhaps some compatibility issue with my OS and Xcode version. I'm running macOS High Sierra and Xcode 9.

After running `./configure` successfully, I am getting the following when running `make`:
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:21:59: warning: unused parameter 'inRefCon' [-Wunused-parameter]
static OSStatus audioCallback(void                       *inRefCon,
                                                          ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:22:59: warning: unused parameter 'ioActionFlags' [-Wunused-parameter]
                              AudioUnitRenderActionFlags *ioActionFlags,
                                                          ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:23:59: warning: unused parameter 'inTimeStamp' [-Wunused-parameter]
                              const AudioTimeStamp       *inTimeStamp,
                                                          ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:24:58: warning: unused parameter 'inBusNumber' [-Wunused-parameter]
                              UInt32                     inBusNumber,
                                                         ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:25:58: warning: unused parameter 'inNumberFrames' [-Wunused-parameter]
                              UInt32                     inNumberFrames,
                                                         ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:106:2: error: use of undeclared identifier 'Component'
        Component comp;
        ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:107:2: error: unknown type name 'ComponentDescription'; did you mean 'AudioComponentDescription'?
        ComponentDescription desc;
        ^~~~~~~~~~~~~~~~~~~~
        AudioComponentDescription
/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioComponent.h:270:3: note: 'AudioComponentDescription' declared here
} AudioComponentDescription;
  ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:117:2: error: use of undeclared identifier 'comp'
        comp = FindNextComponent (NULL, &desc);
        ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:117:9: warning: implicit declaration of function 'FindNextComponent' [-Wimplicit-function-declaration]
        comp = FindNextComponent (NULL, &desc);
               ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:118:6: error: use of undeclared identifier 'comp'
        if (comp == NULL) {
            ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:123:11: warning: implicit declaration of function 'OpenAComponent' [-Wimplicit-function-declaration]
        result = OpenAComponent (comp, &outputAudioUnit);
                 ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:123:27: error: use of undeclared identifier 'comp'
        result = OpenAComponent (comp, &outputAudioUnit);
                                 ^
/Users/lucas/Downloads/OpenDUNE-master/src/audio/dsp_osx.c:165:11: warning: implicit declaration of function 'CloseComponent' [-Wimplicit-function-declaration]
        result = CloseComponent(outputAudioUnit);
                 ^

**Comment by miniupnp** [comment]
you need to install libsdl2 and libsdl2-image : 
https://www.macports.org/ports.php?by=name&substr=libsdl2
or
http://brewformulas.org/Sdl2

**Comment by allcentury** [comment]
I also had to install http://brewformulas.org/Sdl2Image
