### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [OpenDUNE/OpenDUNE#317]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [hqxInit](https://github.com/OpenDUNE/OpenDUNE/blob/fd774fa73716ffccb186a1b0eff24fe1d96ab092/src/video/hqx_init.c#L24)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [File constructor](https://github.com/OpenDUNE/OpenDUNE/blob/fd774fa73716ffccb186a1b0eff24fe1d96ab092/src/depend/depend.cpp#L73)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by miniupnp** [comment]
you know OpenDUNE is a port of a MSDOS game, don't you ?
What kind of error situations do you think must be detected more early as it is currently ?

**Comment by elfring** [comment]
There are still more return values ignored from function calls.
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for this software?

**Comment by miniupnp** [comment]
please open issues on precises issues

**Comment by elfring** [comment]
* Would you like to find remaining open issues by corresponding tools?
* How much can development methodology help to improve also this software further?
