### ISSUE TITLE
Keyboard issue on Haiku (my port)

### ISSUE THREAD

**Issue by theclue** [OpenDUNE/OpenDUNE#324]
Good evening,

this is not exactly an issue but rather a request for advices/support.

I'm porting OpenDUNE on Haiku. The port works and the game is playable, although with no sound, with a minor patch you can fine [here](https://github.com/theclue/haikuports/blob/opendune/games-strategy/opendune/patches/opendune-0.9.patchset) (mostly related to system paths). This is based on OpenDUNE v0.9 release.

The game builds well on both SDL and SDL2, but with the latter is extremely slow, so I rever back to SDL for now.

But I have a serious issue with keyboard: basically all the keys are totally messed up (for example, hitting 'n' send the code for '9'). I noticed it while naming a savegame.

The issue goes away with SDL2 (but as I said, the game is unplayable with SDL2).

Do you have an idea on what could cause the issue?

**Comment by miniupnp** [comment]
the PC keyboard scan codes are guessed from the SDL scancodes. I guess they are wrong when running on Haiku (but right on linux)
https://github.com/OpenDUNE/OpenDUNE/blob/master/src/video/video_sdl.c#L651

**Comment by miniupnp** [comment]
@theclue have you been able to look at which scancodes values are given in event.key.keysym.scancode ?
You can check the values for a few keys ESC, the spacebar, etc.
and compare with the PC/AT scancodes https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html

**Comment by miniupnp** [comment]
OK so a mapping from SDL or Haiku (Be) keycodes back to PC scan code has to be done...

**Comment by pulkomandy** [comment]
The keycodes used in Haiku are as defined here: https://www.haiku-os.org/docs/api/keyboard.html
It seems the OpenDUNE code already includes a translation table for Mac OS, I think a similar approach can be used for Haiku.

**Comment by theclue** [comment]
After a couple of years, I'm going to resurrect the porting to Haiku. So I was wondering if the project is still active and if there're some chances to have support on this.

Additionally, Haiku port additions could be eventually added upstream here, perhaps?

**Comment by miniupnp** [comment]
> After a couple of years, I'm going to resurrect the porting to Haiku. So I was wondering if the project is still active and if there're some chances to have support on this.
> 
> Additionally, Haiku port additions could be eventually added upstream here, perhaps?

well I wil happily consider any pull request to add Haiku support.
