### ISSUE TITLE
sound does not work

### ISSUE THREAD

**Issue by flip111** [OpenDUNE/OpenDUNE#329]
in installed the libpulse-dev package as commented here https://github.com/OpenDUNE/OpenDUNE/issues/283#issuecomment-286216238

During configure i see:
```
checking asound... found
checking oss... not found
checking pulse... found
checking munt... not found
```
So i should have asound and pulse working

However when running the game:
```
No valid MIDI output ports.
  Please install and start Timidity++ like: timidity -iA
```

system: ubuntu 18.10

**Comment by miniupnp** [comment]
why don't you install timidity as asked ?

music under linux is played with either MUNT or Timidity

**Comment by flip111** [comment]
This step is not in the readme. And also configure doesn't detect timidity presence

**Comment by flip111** [comment]
i tried with timidity .. this works now, but is a bit stupid that i need to start timidity on the terminal first ..

**Comment by flip111** [comment]
The sound stutters sometimes

**Comment by miniupnp** [comment]
you can also have another MIDI expander. timidity is just a software MIDI expander.

**Comment by flip111** [comment]
i'm not sure how this works, what are my options ?

**Comment by miniupnp** [comment]
https://www.youtube.com/watch?v=kQADZeB-z8M
