### ISSUE TITLE
Extra calls to Tools_Random_256 in Tile_PackTile macro

### ISSUE THREAD

**Issue by evgeniysergeev** [OpenDUNE/OpenDUNE#331]
https://github.com/OpenDUNE/OpenDUNE/blob/1fd55812859dfe85c574b793e237b6500ee72d0c/src/map.c#L1591

```
packed = Tile_PackTile(Tile_MoveByRandom(tile, Tools_Random_256() & 0x3F, true));
```

`Tile_PackTile` is a macro and `Tile_MoveByRandom` called twice here because of that.
The difference is 3 or 6 calls to `Tools_Random_256()` in this line. Resulting map can differ because of different `Tools_Random_256()` in next calls.

Is that expected and works like in original or is this a bug ?

**Comment by miniupnp** [comment]
it is probably a bug.
