### ISSUE TITLE
Help running on Linux Mint 19 with sound

### ISSUE THREAD

**Issue by rsantellan** [OpenDUNE/OpenDUNE#334]
Hi, I have run open dune in my old laptop with linux mint 17, after a fresh reinstall with linux mint 19 (End of life support) I can't hear sound of the voice in the intro and can't start a game.

I have installed 
`
sudo apt install libsdl2-dev timidity timidity-daemon -y
`
I attached the output of the configure and make
[configure-make-output.txt](https://github.com/OpenDUNE/OpenDUNE/files/3464313/configure-make-output.txt)

Is there any more steps I need to do ?
Regards

**Comment by miniupnp** [comment]
hum when the game can't start it is because the sound doesn't play :)

**Comment by miniupnp** [comment]
```
[SRC] Compiling and linking depend
make[1]: g++: Command not found
```
that's not good...

`[SRC] Compiling audio/dsp_pulse.c
`
it looks like it uses pulse audio, try disabling it

**Comment by rsantellan** [comment]
Is there a flag to disable it or I have to disable the system pulse audio ?
Regards

**Comment by miniupnp** [comment]
I guess it is something like
`$ ./configure --without-pulse`

**Comment by rsantellan** [comment]
Thanks @miniupnp now is working like a charm!!
