### ISSUE TITLE
a for loop seems done for nothing.

### ISSUE THREAD

**Issue by Raffaello** [OpenDUNE/OpenDUNE#340]
I have notice this for loop in the remap drawing sprite routing:

https://github.com/OpenDUNE/OpenDUNE/blob/master/src/gui/gui.c#L1348

here the snippet:
````c
int16 i;
v = palette[v];
for(i = 0; i < remapCount; i++) v = remap[v];  /// <=== this for loop can be simply removed?
*buf = v;
buf += buf_incr;
count--;
````

the for loop is repeateing the same **exact** statement, there is no changes with `i`.

is this intedend or is it a mistake? i am puzzled...

**Comment by miniupnp** [comment]
_i_ is only the loop counter and yes, this is the intend of a loop to repeat the exact same statement (that's what is a loop)

how would you rewrite the code differently ?

**Comment by Raffaello** [comment]
> _i_ is only the loop counter and yes, this is the intend of a loop to repeat the exact same statement (that's what is a loop)
> 
> how would you rewrite the code differently ?

i meant but wouldn't be enough just the `v= remap[v];` statement without the for-loop? 

i don't see the "purpose" of that..

wouldn't be better in this way?
```c
if (remapCount == 0) v = palette[v];
else v = remap[v]; 
*buf = v;
buf += buf_incr;
count--;
```

sort of. 

anyway not an issue indeed.

**Comment by TrueBrain** [comment]
Short answer: those two blobs don't do the same :)

`for(i = 0; i < remapCount; i++) v = remap[v];`

Let's break it down: say, `remapCount` is 5. Now let's unroll the loop:

```
v = remap[v];
v = remap[v];
v = remap[v];
v = remap[v];
v = remap[v];
```

Every time the `v` value changes. Maybe you missed that part, where the variable `v` is used on both sides of the assignment? If we put this in values, lets say `remap` is simple `1, 2, 3, 4, 5, 6, 7, ...`, you get with an initial value of `v = 0`:

```
v = remap[v] -> v = remap[0] -> v = 1
v = remap[v] -> v = remap[1] -> v = 2
v = remap[v] -> v = remap[2] -> v = 3
v = remap[v] -> v = remap[3] -> v = 4
v = remap[v] -> v = remap[4] -> v = 5
```

Here you can clearly see that v is not simply `remap[0]`, but in fact a lot of iterations.

Of course I might have completely misunderstood what you meant to say, but to me it reads you missed the fact that `v` is on both sides of the assignment. Am I correct? :D

**Comment by Raffaello** [comment]
> Short answer: those two blobs don't do the same :)
> 
> `for(i = 0; i < remapCount; i++) v = remap[v];`
> 
> Let's break it down: say, `remapCount` is 5. Now let's unroll the loop:
> 
> ```
> v = remap[v];
> v = remap[v];
> v = remap[v];
> v = remap[v];
> v = remap[v];
> ```
> 
> Every time the `v` value changes. Maybe you missed that part, where the variable `v` is used on both sides of the assignment? If we put this in values, lets say `remap` is simple `1, 2, 3, 4, 5, 6, 7, ...`, you get with an initial value of `v = 0`:
> 
> ```
> v = remap[v] -> v = remap[0] -> v = 1
> v = remap[v] -> v = remap[1] -> v = 2
> v = remap[v] -> v = remap[2] -> v = 3
> v = remap[v] -> v = remap[3] -> v = 4
> v = remap[v] -> v = remap[4] -> v = 5
> ```
> 
> Here you can clearly see that v is not simply `remap[0]`, but in fact a lot of iterations.
> 
> Of course I might have completely misunderstood what you meant to say, but to me it reads you missed the fact that `v` is on both sides of the assignment. Am I correct? :D

whops! you are right. i missed that part that v is mutating.
