### ISSUE TITLE
CTRL key disables the keyboard

### ISSUE THREAD

**Issue by lonemadmax** [OpenDUNE/OpenDUNE#345]
I've removed the following line and it seems to work, but I don't know if that's correct or why that code is there:
https://github.com/OpenDUNE/OpenDUNE/blob/2b8a01eb7b4aaa948e413f7445c022073c8574fa/src/input/input.c#L209

From what I see, that's in the "game" key handler, and it would say that when that bit is set, the event is not processed further, making it impossible to clear the bit and making all key events end there (except the non-game alt-enter and company that are processed without sending them to that handler).

I should also mention that this is with some changes to the scancode/keysym stuff in video_sdl.c to adapt that to my system. Maybe in other systems the CTRL key doesn't even get to Input_EventHandler and there's no problem, but then why that line?

**Comment by miniupnp** [comment]
please check with the original DUNE 2 game to see if it is the intended behavior.

**Comment by lonemadmax** [comment]
It isn't. In the mentat screens it acts as any other key to advance text. In the scenario it doesn't do anything, in particular it doesn't disable the keyboard with no way to activate it again. Even if it did, it would be a bug unless there was some other key to reactivate it.

**Comment by miniupnp** [comment]
I traced this code back to efcdbaea67b01c508163c3074365e541beb710f1

with the SDL2 backend the left ctrl doesn't do it to this anyway 
`Unhandled key scancode=0xE0 sym=0x400000E0 Left Ctrl` 

@lonemadmax what are your build options ?

**Comment by miniupnp** [comment]
I think something has been lost in translation ;)
```
	emu_testb(&emu_get_memory8(emu_cs, 0x00, 0x239), 0x4);
	if ((emu_get_memory8(emu_cs, 0x00, 0x239) & 0x4) == 0) goto l__0E60;
	emu_cmpb(&emu_al, 0x5A);
	if (emu_al != 0x5A) { /* Unresolved jump */ emu_ip = 0x0E5D; emu_last_cs = 0x29E8; emu_last_ip = 0x0E4A; emu_last_length = 0x0025; emu_last_crc = 0xF6E4; emu_call(); return; }
	emu_cmpb(&emu_get_memory8(emu_cs, 0x00, 0xAE), 0x1);
	if (emu_get_memory8(emu_cs, 0x00, 0xAE) == 0x1) { /* Unresolved jump */ emu_ip = 0x0E5D; emu_last_cs = 0x29E8; emu_last_ip = 0x0E52; emu_last_length = 0x0025; emu_last_crc = 0xF6E4; emu_call(); return; }
	emu_testw(&emu_dx, 0x80);
	if ((emu_dx & 0x80) != 0) { /* Unresolved jump */ emu_ip = 0x0E5D; emu_last_cs = 0x29E8; emu_last_ip = 0x0E58; emu_last_length = 0x0025; emu_last_crc = 0xF6E4; emu_call(); return; }
	goto l__0F4E;
l__0E60:
```
was translated to 
```
if ((s_input_local->activeInputMap[7] & 0x4) != 0) goto event_exit;
```

**Comment by miniupnp** [comment]
there is something that should happen if `al == 05Ah && cs:[0AEh] != 1 && (dx AND 080h)`

**Comment by glx22** [comment]
Indeed E5D is just `emu_orb(&emu_ah, 0x2)` (`state |= 0x02`) inserted between `goto l__0F4E;` (E5A) and `l__0E60:` (E60)
And it should also be done when `key != 05Ah || cs:[0AEh] == 1 || (dx & 080h)`
There's also
```
	emu_testb(&emu_get_memory8(emu_cs, 0x00, 0x23A), 0x1);
	if ((emu_get_memory8(emu_cs, 0x00, 0x23A) & 0x1) != 0) { /* Unresolved jump */ emu_ip = 0x0E5D; emu_last_cs = 0x29E8; emu_last_ip = 0x0E3E; emu_last_length = 0x0025; emu_last_crc = 0xF6E4; emu_call(); return; }
```
right before `if ((s_input_local->activeInputMap[7] & 0x4) != 0)` bypassing all the checks and jumping to E5D

**Comment by miniupnp** [comment]
5Ah is NUMLOCK

**Comment by miniupnp** [comment]
`if ((emu_get_memory8(emu_cs, 0x00, 0x23A) & 0x1) != 0)` is
`if ((s_input_local->activeInputMap[8] & 0x1) != 0)`
=> checking key 0x40 which is RCTRL

@glx22 what is` cs:[0AEh]` ?

**Comment by miniupnp** [comment]
@lonemadmax does my branch https://github.com/miniupnp/OpenDUNE/tree/keyboard-input fix your issue ?

**Comment by glx22** [comment]
`cs:[0AEh]` seems to be a bool set to true only if `0x40:[0x96] & 0x10 != 0` and it seems this test never returned true so the `cs:[0AEh]` was always false, and removed in the translation (l__0D77).
I can't remember what was in segment `0x40` but above this there was also some flag checks of `0x40:[017h]` and `cs:[1B5h]` (controlKeys) is set accordingly, but that was also discarded.
`emu_dx` contains some global flags (0x353F:[700Eh]) copied into `cs:[1B3h]` (flags), and this part is also discarded in the translation.

So I think your fix is correct. Discarded stuff is probably related to some specific DOS stuff.

**Comment by lonemadmax** [comment]
@miniupnp your branch does fix the issue, thank you.

It doesn't seem you need my build options anymore, but just in case: I'm only using --disable-assert and the several options to set the different directories and the binary name. Although I don't pass any option to set the SDL version, as you've guessed it's SDL 1.2 what I have here, not SDL2.

**Comment by miniupnp** [comment]
it looks like CTRL + numeric keypad is used to emulate mouse movement.
To try with NUMLOCK on or OFF and with SHIFT down or up.

**Comment by miniupnp** [comment]
about 40h:96h : https://stanislavs.org/helppc/bios_data_area.html
```
40:96	byte	Keyboard mode/type

		|7|6|5|4|3|2|1|0| Keyboard mode/type
		 | | | | | | | `--- last code was the E1 hidden code
		 | | | | | | `---- last code was the E0 hidden code
		 | | | | | `----- right CTRL key depressed
		 | | | | `------ right ALT key depressed
		 | | | `------- 101/102 enhanced keyboard installed
		 | | `-------- force num-lock if Rd ID & KBX
		 | `--------- last char was first ID char
		 `---------- read ID in process
```
