### ISSUE TITLE
Option to scale game window x2 or x3 and so on.

### ISSUE THREAD

**Issue by Sturwandan** [OpenDUNE/OpenDUNE#354]
It would be nice if OpenDUNE could scale the window up at least by integer coefficients. On modern displays the window is just so tiny it's unplayable.

**Comment by miniupnp** [comment]
It is indeed nice that OpenDUNE can scale the window up by integer coefficients : 
https://github.com/OpenDUNE/OpenDUNE/blob/master/README.txt#L60
