### ISSUE TITLE
Build fails with GCC 10

### ISSUE THREAD

**Issue by Mailaender** [OpenDUNE/OpenDUNE#356]
I packaged it successful for @openSUSE Leap 15.2. On the rolling release Tumbleweed with gcc10 I get a weird error message:

```
configure: error: gcc older than 3.3 can't compile OpenDUNE because of its poor template support
error: Bad exit status from /var/tmp/rpm-tmp.WjAvXU (%build)
```

https://build.opensuse.org/request/show/859277

**Comment by miniupnp** [comment]
@Mailaender 
which commit ?

does it includes eda13846f82cb39344889fce07f23f31ea4607d1 ?

**Comment by miniupnp** [comment]
@Mailaender  can you check that #357 fixes it ?

**Comment by Mailaender** [comment]
None of them help.

**Comment by miniupnp** [comment]
@Mailaender what is the output of `gcc -dumpversion`

**Comment by Mailaender** [comment]
> 10

**Comment by miniupnp** [comment]
ok. Just 10, not 10.0 or something ?

**Comment by Mailaender** [comment]
Just 10.

**Comment by miniupnp** [comment]
@Mailaender could you try with 411c3a9d2608767f6491d2f2da441bcb84fe64d4 ?

**Comment by Mailaender** [comment]
Fix confirmed: https://build.opensuse.org/request/show/881282

**Comment by miniupnp** [comment]
thanks !
