### ISSUE TITLE
Game Crush: End of Mission 1 (Atreides)

### ISSUE THREAD

**Issue by Albeoris** [OpenDUNE/OpenDUNE#360]
The game crashes after entering a name in the leaderboard. 
Each next start of the game also leads to a crash. 
Deleting save files doesn't help. 

[crash.log](https://github.com/OpenDUNE/OpenDUNE/files/6563994/crash.log)

I cannot provide a dump.

**Comment by miniupnp** [comment]
please try the latest sources from the master branch
