### ISSUE TITLE
what do i have to write in this opendune.ini to change language?

### ISSUE THREAD

**Issue by o0Julia0o** [OpenDUNE/OpenDUNE#371]
hi,

what do i have to write in this opendune.ini to change language?

**Comment by Xaroth** [comment]
The `language` setting in opendune.ini can be one of the following:
- `english`
- `french`
- `german`
- `italian`
- `spanish`

The check is case insensitive, so for config purposes, `English` is the same as `englisH` etc.

I am not 100% if the non-English translations are fully functional, so YMMV.

**Comment by o0Julia0o** [comment]
thank you
