### ISSUE TITLE
Midi sound playback on Windows 10

### ISSUE THREAD

**Issue by xcom169** [OpenDUNE/OpenDUNE#375]
Hello All!

How can I use a better MIDI player like Fluidsynth with a good soundfont on Win 10?
I assume OpenDUNE always use the built-in MIDI which is not so good quality.  
![image](https://user-images.githubusercontent.com/17802090/199928059-edfdce28-dee6-4fed-929c-0093456a7f30.png)
 

Thanks

**Comment by miniupnp** [comment]
Isn't there documentation to use MUNT ?

**Comment by miniupnp** [comment]
Win32 MIDI code selects the device 0 unless mt32midi is selected.
https://github.com/OpenDUNE/OpenDUNE/blob/master/src/audio/midi_win32.c#L17

How would you like this to be improved ?

**Comment by xcom169** [comment]
Is it possible to add a command line argument, so the user can choose the device ID  1,2 .. 9 ?
For example :  opendune.exe  -MidiDev 1    ?

**Comment by xcom169** [comment]
Thanks a lot

**Comment by miniupnp** [comment]
sorry for the loooong delay ;)
