### ISSUE TITLE
[macOS] [Arm] [SDL HW] Graphics issue with animations and mouse movement

### ISSUE THREAD

**Issue by shinra-electric** [OpenDUNE/OpenDUNE#377]
I built OpenDune for Arm on macOS Ventura, and there are graphics issues. 

During the intro, garbage is shown around the animation: 

<img width="752" alt="Screenshot 2023-03-20 at 15 56 42" src="https://user-images.githubusercontent.com/50119606/226386616-fd87be68-282b-4e9e-b7e7-d46a43da454b.png">

This also manifests around animations (such as speaking characters when you're choosing a house): 
<img width="1392" alt="Screenshot 2023-03-20 at 16 24 57" src="https://user-images.githubusercontent.com/50119606/226387614-edef707f-f970-4bda-89e5-1ea7a4236813.png">

And also around the mouse pointer, but only when moving (I was moving the mouse fast just to illustrate): 
<img width="641" alt="Screenshot 2023-03-20 at 16 06 27" src="https://user-images.githubusercontent.com/50119606/226387195-2c6fbc4f-c85f-45fe-9c03-2c20a5e824c2.png">

**Comment by miniupnp** [comment]
it may be an issye with SDL ?

**Comment by shinra-electric** [comment]
If it helps, here are the terminal outputs after building and running: 

[OpenDune_build.txt](https://github.com/OpenDUNE/OpenDUNE/files/11037667/OpenDune_build.txt)
[OpenDune_running.txt](https://github.com/OpenDUNE/OpenDUNE/files/11037669/OpenDune_running.txt)

**Comment by miniupnp** [comment]
@shinra-electric does the problem persists with the latest SDL2 version ?

**Comment by shinra-electric** [comment]
I just made a fresh build, and yes the issue is still there:
<img width="1392" alt="Screenshot 2024-03-03 at 11 11 42" src="https://github.com/OpenDUNE/OpenDUNE/assets/50119606/cf6e8966-9b95-41a7-82b5-801c824f7f75">

**Comment by miniupnp** [comment]
without reproducing it is difficult to understand what happens.

**Comment by dalanmiller** [comment]
Also experiencing this on my M1 Max

**Comment by shinra-electric** [comment]
After the above comment I tried it on an old Intel Mac, and it works fine. 

So this issue seems to be with Arm64 Macs only.

**Comment by binglongx** [comment]
I am not able to create a branch (so no PR) here, but this is a fix that works on my Mac with Apple Silicon M1, see attached git diff file.

The change basically allows configuring opendune to run with renderer software fallback. In M1 Macs, using software fallback for renderer overcomes the messed up graphics.

To take effect, add to `opendune.ini`:

```
[opendune]
renderer_software_fallback=1
```
[Issue377.patch](https://github.com/OpenDUNE/OpenDUNE/files/15229600/Issue377.patch)

**Comment by miniupnp** [comment]
fixed with 8f5e52efd83f7e167a917101342113883914bc4c
