### ISSUE TITLE
When i open Dunedynasty.exe, i get an error "Unable to open RegionH.ini"

### ISSUE THREAD

**Issue by archie987** [OpenDUNE/OpenDUNE#378]
Hi guys,

any help with this one?

When i open Dunedynasty.exe, i get an error "Unable to open RegionH.ini".  Screenshot attached. 
![DuneDynastyError](https://github.com/OpenDUNE/OpenDUNE/assets/134841538/13690e83-5622-49fd-866a-8d8019efc97b)

**Comment by archie987** [comment]
Oh, this is windows 10, 64bit.

**Comment by Xaroth** [comment]
Hi,

Dune Dynasty is a different project from OpenDUNE, so you might want to file a ticket on their project tracker ( https://dunedynasty.sourceforge.net/ ). From the looks of it I would guess that you are missing some data files, or the datafiles you have are incompatible with Dune Dynasty.
