### ISSUE TITLE
[macOS] datadir: Shortcuts such as `$HOME/` or `~/` do not work in the datadir path

### ISSUE THREAD

**Issue by shinra-electric** [OpenDUNE/OpenDUNE#391]
I want to keep the data folder in Application Support, so I'm trying to edit the `datadir` path in the `.ini`. 

If I hard-code a path such as `/Users/[my_username]/Library/Application Support/OpenDUNE/data` the data folder is located correctly. 

However, when using a shorthand for the user directory such as `$HOME` or `~` the data folder isn't found. 

It's preferable to abstract away the user path so that it doesn't matter if the username changes. 

Edit: To clarify, I think one of the default search paths for datadir on macOS should be `~/Library/Application Support/OpenDUNE/data`

**Comment by miniupnp** [comment]
> Edit: To clarify, I think one of the default search paths for datadir on macOS should be ~/Library/Application Support/OpenDUNE/data

The "personal files" directory is set to "${HOME}/Library/Application Support/OpenDUNE"
but the data file directory to subdirectory data in the bundle path.

https://github.com/OpenDUNE/OpenDUNE/blob/master/src/file.c#L576

Isn't it more logical to put global data in the application bundle ?

**Comment by shinra-electric** [comment]
There are arguments for both, and the game should probably search in both locations

Data folder in app bundle:
Pros: 
- The app bundle can be self-contained. Many people would like this because it can be moved around and distributed in just one file. 

Cons: 
- Each time a new version of the app is built/released, the game data needs to be recovered from the old version and inserted into the new one.
- Changing the contents of an app bundle invalidates its signature
- Changing the contents of an app bundle is not easy for non-technical people, and not standard practice (for the reason above). 

Data in the Application Support Folder
Pros: 
- No need to worry about the game data when updating the app
- No need delve into the app, so the signature is not affected

Cons:
- The game is no longer self-contained

If you look at other [source ports on macOS](https://www.macsourceports.com/) you can see that the majority look for their game data in Application Support.

**Comment by miniupnp** [comment]
@shinra-electric is #393 OK for you ?

**Comment by shinra-electric** [comment]
Yes, it works perfectly. Thanks!
