### ISSUE TITLE
Build Failure?

### ISSUE THREAD

**Issue by liyun-li** [OpenDUNE/OpenDUNE#405]
Hi there, I checked the wiki but didn't see a build guide so I just did `./configure` and `make`, but `make` yields the following error. Adding `0`, `1` or `2` back works though. Is this intended?

```
/OpenDUNE/src/rev.c:39:44: error: expected expression before ‘;’ token
   39 | const uint8 g_opendune_revision_modified = ;
      |                                            ^
make[1]: *** [Makefile:185: rev.o] Error 1
```

**Comment by miniupnp** [comment]
`rev.c` is generated. There is a problem with the generation here.

**Comment by miniupnp** [comment]
https://github.com/OpenDUNE/OpenDUNE/blob/master/Makefile.src.in#L207

**Comment by miniupnp** [comment]
@liyun-li if the build system fails to fill the value `g_opendune_revision_modified` you can set it manually to 0, 1 or 2 :smiley:
