### ISSUE TITLE
Linux - deadlock between alsa and xcb

### ISSUE THREAD

**Issue by OpenDUNE** [OpenDUNE/OpenDUNE#93]
http://bugs.opendune.org/view.php?id=93

svuorela wrote:
...according to #opendune it is related to alsa and xcb with one doing free and the other malloc at the same time.

The backtrace is here:

gdb) bt
#0 0xb7796424 in __kernel_vsyscall ()
0000001 0xb753adb1 in __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/i386/i686/../i486/lowlevellock.S:95
0000002 0xb74d1ba7 in _L_lock_9661 () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
0000003 0xb74d03d6 in *__GI___libc_free (mem=0xb201efd8) at malloc.c:3736
0000004 0xb72e4959 in dequeue_pending_request (dpy=<optimized out>, req=<optimized out>) at ../../src/xcb_io.c:195
0000005 0xb72e5ccf in _XReply (dpy=0x8890a40, rep=0xbfaf7d80, extra=0, discard=1) at ../../src/xcb_io.c:638
0000006 0xb72e1236 in XSync (dpy=0x8890a40, discard=0) at ../../src/Sync.c:44
0000007 0xb76f1410 in ?? () from /usr/lib/libSDL-1.2.so.0
0000008 0xb76e3a6e in SDL_UpdateRects () from /usr/lib/libSDL-1.2.so.0
0000009 0xb76e3bd1 in SDL_UpdateRect () from /usr/lib/libSDL-1.2.so.0
0000010 0x0809adfc in Video_Tick () at /home/pusling/games/opendune/opendune-0.7-source/src/video/video_sdl.c:524
0000011 0x080944b6 in Timer_InterruptRun () at /home/pusling/games/opendune/opendune-0.7-source/src/timer.c:103
0000012 <signal handler called>
0000013 _int_malloc (av=<optimized out>, bytes=<optimized out>) at malloc.c:4348
0000014 0xb74cfc1b in __libc_calloc (n=1, elem_size=36) at malloc.c:4065
0000015 0xb741a1ee in pa_xmalloc0 () from /usr/lib/libpulse.so.0
0000016 0xb7401681 in ?? () from /usr/lib/libpulse.so.0
0000017 0xb70dec79 in pa_pdispatch_register_reply () from /usr/lib/libpulsecommon-0.9.23.so
0000018 0xb740ccdf in pa_stream_update_timing_info () from /usr/lib/libpulse.so.0
0000019 0xb740cf4d in ?? () from /usr/lib/libpulse.so.0
0000020 0xb7410586 in pa_stream_cork () from /usr/lib/libpulse.so.0
0000021 0xb7764480 in ?? () from /usr/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
0000022 0xb7650b69 in ?? () from /usr/lib/i386-linux-gnu/libasound.so.2
0000023 0xb76045df in snd_pcm_start () from /usr/lib/i386-linux-gnu/libasound.so.2
0000024 0xb760c777 in ?? () from /usr/lib/i386-linux-gnu/libasound.so.2
0000025 0xb76503bf in ?? () from /usr/lib/i386-linux-gnu/libasound.so.2
0000026 0xb76052a4 in snd_pcm_writei () from /usr/lib/i386-linux-gnu/libasound.so.2
0000027 0x080562aa in DSP_Play (data=0x88cad72 "\001(\"") at /home/pusling/games/opendune/opendune-0.7-source/src/audio/dsp_alsa.c:134
0000028 0x08055994 in Driver_Voice_Play (data=0x88cad58 "Creative Voice File\032\032", arg0A=11) at /home/pusling/games/opendune/opendune-0.7-source/src/audio/driver.c:272
0000029 0x08059006 in Voice_PlayAtTile (voiceID=42, position=...) at /home/pusling/games/opendune/opendune-0.7-source/src/audio/sound.c:128
0000030 0x08098e13 in Unit_CreateBullet (position=..., type=UNIT_MISSILE_TURRET, houseID=1 '\001', damage=30, target=16420) at /home/pusling/games/opendune/opendune-0.7-source/src/unit.c:1936
0000031 0x08089cf0 in Script_Structure_Fire (script=0x80c9074) at /home/pusling/games/opendune/opendune-0.7-source/src/script/structure.c:534
0000032 0x08088512 in Script_Run (script=0x80c9074) at /home/pusling/games/opendune/opendune-0.7-source/src/script/script.c:445
0000033 0x0808fe5f in GameLoop_Structure () at /home/pusling/games/opendune/opendune-0.7-source/src/structure.c:333
0000034 0x08082c8c in GameLoop_Main () at /home/pusling/games/opendune/opendune-0.7-source/src/opendune.c:2281
0000035 0x08082eeb in main (argc=1, argv=0xbfaf8ea4) at /home/pusling/games/opendune/opendune-0.7-source/src/opendune.c:2396

**Comment by miniupnp** [comment]
More than 2 years after, I made my mind and found a solution using pause() to wait for the SIGALRM in the "main thread" to execute Timers with the right timing.
Only very rarely there are some "interrupts" lost (ie sleepIdle() is not called before the timer is triggered). It happens mostly during startup, not during game.
I need to play some more on my old and slow Mac to see how it behaves

**Comment by miniupnp** [comment]
see https://github.com/OpenDUNE/OpenDUNE/pull/261
